homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 2
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

zone:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  radius: 200
  icon: mdi:home

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  trusted_networks:
    - 192.168.1.0/24

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: darksky
    api_key: d1bc8cdce2115477573d6e7a9d04f538
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance

# Text to speech
tts:
  platform: google

device_tracker:
- platform: bluetooth_tracker
- platform: owntracks 
- platform: icloud
  username: !secret device_tracker_email
  password: !secret device_tracker_password
  interval_seconds: 12
  consider_home: 200

zwave:
  usb_path: /dev/ttyUSB0

mqtt:
  broker: 192.168.1.224
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password


script:
  family_room:
    hidden: true
    sequence:
      - service: switch.turn_off
        entity_id: switch.family_room_light_switch_2_0

